name 'MariaDB'
maintainer 'Dave Bartlett'
maintainer_email 'Dave@example.com'
license 'Apache 2.0'
description 'Installs/Configures mariaDB'
long_description 'Installs/Configures mariaDB'
version '0.2.0'
source_url 'https://github.com/DaveB101/mariaDB_cookbook'
chef_version '>= 12.1' if respond_to?(:chef_version)
supports 'ubuntu'
